New CircleCI config folder and yml file
metaneuro/concept_query pull request #102
Opened 2021-12-10 21:44 UTC by jarmoza

2021-12-13 14:23 UTC, surchs requested changes

2021-12-13 14:23 UTC, surchs commented on .circleci/config.yml
> +  build-docker-image-only:
@jarmoza: I believe this workflow is meant to upload the container to Dockerhub. It is failing because it expects login credentials. For starters, we should just get the simple testing workflow running. Then we can take a look at using circleCI to push new docker images.

2021-12-13 22:13 UTC, surchs commented
@jarmoza I think you can get the geckodriver to work following these docs: https://circleci.com/developer/orbs/orb/circleci/browser-tools

2021-12-13 23:08 UTC, surchs commented
Ah well, guess I was prematurely optimistic. Just for future reference: what is failing here isn't the functional test itself (that will also fail) but rather the dependencies of the test runner (geckodriver). We could probably get them to work, but then we'd still be unable to run the functional test against the graph. So for now I removed the functional test again.

Let's clean up the files, then we should be good to merge.
Since we have both added a bunch of test commits here, I'd suggest we merge the PR by squash and merge (see [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits))

2021-12-14 17:36 UTC, surchs commented on .circleci/config.yml
> +  # build_and_test:
can we remove these comments?

2021-12-14 17:39 UTC, surchs commented on .circleci/config.yml
> +      - run:
same here, is this used anywhere?

2021-12-14 17:41 UTC, surchs commented on .circleci/config.yml
> +  test:
I think this step is not needed, we can just run the tests inside the build step (see [here](https://circleci.com/docs/2.0/language-python/)). 
Currently the setup section is duplicated between the two

2021-12-14 17:42 UTC, surchs commented on .circleci/config.yml
> +workflows:
I don't think we are using workflows, right? if we can, let's remove this here

2021-12-14 17:42 UTC, surchs commented on Dockerfile
> +
as far as I understand, this file is not necessary for the testing. Let's remove it from the repo until we do have a use for it.

2021-12-14 17:46 UTC, surchs commented on requirements.txt
> +asgiref==3.4.1
I have two comments here:

1. Let's keep this limited to the actual requirements we have, not all the libraries we have installed here (i.e. just use what was in the pipfile so far)
2. (maybe) Let's not pin the versions. I know this may break things in the future, but let's have it break first before we go this step. Eventually we'll look at poetry (or pipenv again) to resolve dependencies. And this will come back for when we deploy using a docker container. But for now, we should be fine with just the unpinned requirements. Our tests should tell us if that's no longer workable.

2021-12-14 19:44 UTC, jarmoza commented on .circleci/config.yml
> +      - setup_remote_docker
`setup_remote_docker` is the command that indicates we want to build a custom docker image (based on the Dockerfile). This job is currently not run as it is only part of the commented out build/build_and_test workflows.

2021-12-14 19:45 UTC, jarmoza commented on .circleci/config.yml
> +  # build_and_test:
I'd prefer to keep them as they are commented out alternate workflows – or until we implement the solution for switching between CircleCI workflows for building/testing/deployment.

2021-12-14 19:46 UTC, jarmoza commented on .circleci/config.yml
> +      - run:
Yes, it's quite possible this is a redundant command left over from the combined build_and_test workflow. I can switch to the build workflow temporarily and try removing it to see if the docker build still succeeds.

2021-12-14 19:47 UTC, jarmoza commented on .circleci/config.yml
> +  test:
That's right. (I think the comments here are slightly out of order.) This may be a redundancy leftover from the test workflow. Will try removing and building to see if it can be removed.

2021-12-14 19:48 UTC, jarmoza commented on .circleci/config.yml
> +workflows:
In fact, workflow is what's driving the file currently. We are running a workflow that is exclusively `test` at the moment, thus the commented out workflows at the bottom for `build` and `build_and_test`

2021-12-14 19:50 UTC, jarmoza commented on Dockerfile
> +
Are you referring to the Dockerfile itself here? It appears that you're commenting on a blank line in `Dockerfile`. The `Dockerfile` exists for the build workflow, and will also be used if we transition to a `docker-compose.yml` file.

2021-12-14 19:53 UTC, jarmoza commented on requirements.txt
> +asgiref==3.4.1
> 1. Let's keep this limited to the actual requirements we have, not all the libraries we have installed here (i.e. just use what was in the pipfile so far)

I did not explicitly install this library. Did you? It might be a dependency of one of our other packages.

> 2\. (maybe) Let's not pin the versions. I know this may break things in the future, but let's have it break first before we go this step. Eventually we'll look at poetry (or pipenv again) to resolve dependencies. And this will come back for when we deploy using a docker container. But for now, we should be fine with just the unpinned requirements. Our tests should tell us if that's no longer workable.

What's the downside of pinning versions?

2021-12-14 19:55 UTC, jarmoza commented on .circleci/config.yml
> +  build-docker-image-only:
@surchs Yes, we can close this comment. The orb and docker command was just there for experimentation. Unfortunately, when changing the config.yml with CircleCI, in order to test it must be committed to the branch.

2021-12-14 21:16 UTC, surchs commented on .circleci/config.yml
> +      - setup_remote_docker
this can probably go

2021-12-14 23:32 UTC, jarmoza commented
Following changes have been made as requested.

1) Extraneous lines were removed from build and test jobs
2) Build job was tested with those changes – and then commented out
3) Commentary on what the commented-out build job does was added
4) Python test job was re-tested
5) Test job and test workflow has been shifted to the top of each section for clarity
6) Commentary on how workflows work and the current workflow being used ('test') was added
7) Dockerfile was removed and its contents have been noted in the dockerization issue (https://github.com/metaneuro/concept_query/issues/68)
8) `Pipfile` and `Pipfile.lock` were removed
9) The base dependencies from the Pipfile were added to `requirements.txt` with no pinned versions listed
10) All changes have passed the testing currently listed in the `config.yml` on CircleCI as seen here: https://app.circleci.com/pipelines/github/metaneuro/concept_query/45/workflows/04d9420d-1103-4ec5-9628-3082626e8cea/jobs/48

2021-12-14 23:32 UTC, merged